### ISSUE TITLE
Cambiar el logotipo en la pestaña del navegador

### ISSUE THREAD

**Issue by nepito** [RamonMartinez01/front-futliga01#35]
La pestaña del navegador trae el logotipo de Vite. Debemos cambiarlo por el logotipo de la liga.

![image](https://github.com/RamonMartinez01/front-futliga01/assets/35377740/3bd8ea05-6366-42c1-94ef-6b3d30e59849)

**Comment by nepito** [comment]
Quedó al chingazo:
![image](https://github.com/RamonMartinez01/front-futliga01/assets/35377740/a56ed039-7941-4dad-801a-dfe1c02bed47)

**Comment by RamonMartinez01** [comment]
😎😎 La voy a poner de logo en la App también.
